import Head from 'next/head';
import Link from 'next/link';
import { Container } from 'react-bootstrap';
import variables from '../styles/scss/Home.module.scss';
import MyNavbar from '../components/Navbar';
import Homepage from '../components/Home';
import Portfolio from '../components/Portfolio';

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MyNavbar />

      <main className={variables.main} id="top">
        <Homepage />
        <Portfolio />
      </main>

      <footer className={variables.footer}>
        <p className={variables.floatEnd}>
          <Link href="#top" passHref>
            <a>Back to top</a>
          </Link>
        </p>
        <p>
          &copy; 2017–2021 Company, Inc. &middot; <a href="#">Privacy</a>{' '}
          &middot; <a href="#">Terms</a>
        </p>
      </footer>
    </Container>
  );
}
